### ISSUE TITLE
Huge log.txt in %USER%\AppData\Roaming\EyeLeo

### ISSUE THREAD

**Issue by sgorbatiuk** [Yamatao/eyeleoapp#15]
Hello @Yamatao, the application v. 1.34_ru generates huge log [c:\Users\%USER%\AppData\Roaming\EyeLeo\log.txt](https://github.com/Yamatao/eyeleoapp/files/3685756/log.txt) — 22 KB for 12 minutes.
Environment: Windows 10 Enterprise, version 1903, build 18362.387. But IMHO the issue doesn't relate to Win version and build.

**Comment by Yamatao** [comment]
Thank you for the feedback. I will fix that in the closest release.

**Comment by Yukigaru** [comment]
Fixed and will be in the upcoming release.
