### ISSUE TITLE
Feature request - Добавить возможность выбирать разных персонажей в настройках

### ISSUE THREAD

**Issue by catinwarmhands** [Yamatao/eyeleoapp#18]
Здравствуйте!
Спасибо за отличную программу, реально помогает не забывать про здоровье глаз.

Хотелось бы иметь возможность менять путь до папки c изображениями персонажа (Personages\leopard). Так, пользователи можно было бы нарисовать свои картинки, положить их в папку Personages и использовать их.

Сейчас такого же эффекта можно достичь просто заменив оригинальные файлы, но это не удобно.

Заранее спасибо.

**Comment by Yukigaru** [comment]
Hi, 
Thank you for your suggestion!
It's planned to be implemented in version 2.0.
