### ISSUE TITLE
Provide unnecessary libraries to be able to open app

### ISSUE THREAD

**Issue by oscyp** [Yamatao/eyeleoapp#25]
![error](https://user-images.githubusercontent.com/31035071/101528727-efba4280-398f-11eb-8ee8-707a9b863a53.PNG)

App is not starting because of lack some libraries. Win 10 x64.

**Comment by Yamatao** [comment]
Could you please download a new build from the eyeleo.com/download? I've just uploaded fixed installed with the mentioned library. Thanks for the feedback!

**Comment by oscyp** [comment]
@Yamatao it works now, thanks!

Please consider to up the version to 1.3.6.1
